# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: "${{ matrix.config.os }} (R: ${{ matrix.config.r }}, Rust: ${{ matrix.config.rust }})"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release',  rust: 'stable-gnu', rtools-version: '42'}
          - {os: windows-latest, r: 'devel',    rust: 'stable-gnu', rtools-version: '42'}
          - {os: windows-latest, r: 'oldrel',   rust: 'stable-msvc'}
          - {os: macOS-latest,   r: 'release',  rust: 'stable'     }
          - {os: ubuntu-20.04,   r: 'release',  rust: 'stable'     }
          - {os: ubuntu-20.04,   r: 'devel',    rust: 'stable'     }
          - {os: ubuntu-20.04,   r: 'release',  rust: 'nightly'    }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.config.rust }}

      - name: Additional Rust set up for Windows (R >= 4.2)
        if: runner.os == 'Windows' && matrix.config.r != 'oldrel'
        run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup target add x86_64-pc-windows-gnu

      - name: Additional Rust set up for Windows (R < 4.2)
        if: runner.os == 'Windows' && matrix.config.r == 'oldrel'
        run: |
          rustup toolchain uninstall stable
          rustup toolchain install stable
          rustup target add i686-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'

      - name: debug install
        if: always()
        run: cat ./check/*.Rcheck/00install.out
